version: "3.1"

services:
  spk_cli:
    image: mkenjis/ubpyspk_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    ports:
      - 8082:8082
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst

networks:
  mynet:
    external:
       name: mynet
